title: Spaghetti with Pesto
author: alethebro
email: alethebro@github.com
description: > # this means to ignore newlines until "baseurl:"
  Spaghetti are famous italian pasta and usually they are associated to the tomato sauce.
  Do you know that they are very good also with Pesto sauce?
  

# social links
twitter_username: your-twitter-handle
github_username:  alethebro

show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-architect
